# Generated by Django 4.0.3 on 2022-05-11 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('book_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('published', models.IntegerField()),
                ('author', models.CharField(max_length=100)),
                ('domain', models.CharField(max_length=200)),
                ('is_available', models.BooleanField(default=False)),
            ],
        ),
    ]
